#include <stdbool.h>
#include <linux/input.h>

// Guarda de inclusão - evita que o arquivo seja incluído múltiplas vezes
#define KEYMAP_H
// Define o valor máximo para códigos de tecla (0x2ff = 767 em decimal)
// Baseado no KEY_MAX definido em linux/input-event-codes.h
#define KEY_MAX_CODE 0x2ff

int scan_device(char *, size_t ); // Encontra o dispositivo de teclado


/*
 * Array que mapeia códigos de tecla para strings legíveis
 * KEY_MAX_CODE + 1 = 768 posições para cobrir todos os códigos possíveis
 * Usa inicializadores designados do C (C99) [KEY_A] = "A"
 * Teclas não mapeadas ficam como ?
 */
const char *key_code_names[KEY_MAX_CODE + 1]= {
    [KEY_A] = "A",
    [KEY_B] = "B",
    [KEY_C] = "C",
    [KEY_D] = "D",
    [KEY_E] = "E",
    [KEY_F] = "F",
    [KEY_G] = "G",
    [KEY_H] = "H",
    [KEY_I] = "I",
    [KEY_J] = "J",
    [KEY_K] = "K",
    [KEY_L] = "L",
    [KEY_M] = "M",
    [KEY_N] = "N",
    [KEY_O] = "O",
    [KEY_P] = "P",
    [KEY_Q] = "Q",
    [KEY_R] = "R",
    [KEY_S] = "S",
    [KEY_T] = "T",
    [KEY_U] = "U",
    [KEY_V] = "V",
    [KEY_W] = "W",
    [KEY_X] = "X",
    [KEY_Y] = "Y",
    [KEY_Z] = "Z",
    [KEY_1] = "1",
    [KEY_2] = "2",
    [KEY_3] = "3",
    [KEY_4] = "4",
    [KEY_5] = "5",
    [KEY_6] = "6",
    [KEY_7] = "7",
    [KEY_8] = "8",
    [KEY_9] = "9",
    [KEY_0] = "0",
    [KEY_MINUS] = "-",
    [KEY_EQUAL] = "=",
    [KEY_LEFTBRACE] = "[",
    [KEY_RIGHTBRACE] = "]",
    [KEY_BACKSLASH] = "\\",
    [KEY_SEMICOLON] = ";",
    [KEY_APOSTROPHE] = "'",
    [KEY_GRAVE] = "`",
    [KEY_COMMA] = ",",
    [KEY_DOT] = ".",
    [KEY_SLASH] = "/",
    [KEY_ENTER] = "\n",
    [KEY_SPACE] = " ",
    [KEY_BACKSPACE] = "\b",
    [KEY_TAB] = " _tab_ ",
    [KEY_ESC] = " _esc_ ",
    [KEY_CAPSLOCK] = " _caps_ ",
    [KEY_LEFTSHIFT] = " _lsf_ ",
    [KEY_RIGHTSHIFT] = " _rsf_ ",
    [KEY_LEFTCTRL] = " _ctrleft_ ",
    [KEY_RIGHTCTRL] = " _ctrlright_ ",
    [KEY_LEFTALT] = " _leftalt_ ",
    [KEY_RIGHTALT] = " _rightalt_ ",
    [KEY_LEFTMETA] = " _super_ ",
    [KEY_RIGHTMETA] = " _super_ ",
    [KEY_UP] = " _up_ ",
    [KEY_DOWN] = " _down_ ",
    [KEY_LEFT] = " _left_ ",
    [KEY_RIGHT] = " _right_ ",
    [KEY_INSERT] = " _insert_ ",
    [KEY_DELETE] = " _delete_ ",
    [KEY_HOME] = " _home_ ",
    [KEY_END] = " _end_ ",
    [KEY_PAGEUP] = " _pageup_ ",
    [KEY_PAGEDOWN] = " _pagedown_ ",
    [KEY_F1] = " _F1_ ",
    [KEY_F2] = " _F2_ ",
    [KEY_F3] = " _F3_ ",
    [KEY_F4] = " _F4_ ",
    [KEY_F5] = " _F5_ ",
    [KEY_F6] = " _F6_ ",
    [KEY_F7] = " _F7_ ",
    [KEY_F8] = " _F8_ ",
    [KEY_F9] = " _F9_ ",
    [KEY_F10] = " _F10_ ",
    [KEY_F11] = " _F11_ ",
    [KEY_F12] = " _F12_ ",
    [KEY_NUMLOCK] = " _numlock_ ",
    [KEY_KPASTERISK] = "*",
    [KEY_KPMINUS] = "-",
    [KEY_KPPLUS] = "+",
    [KEY_KPDOT] = ".",
    [KEY_KPENTER] = "\n",
    [KEY_KPSLASH] = "/",
    [KEY_KP0] = "0",
    [KEY_KP1] = "1",
    [KEY_KP2] = "2",
    [KEY_KP3] = "3",
    [KEY_KP4] = "4",
    [KEY_KP5] = "5",
    [KEY_KP6] = "6",
    [KEY_KP7] = "7",
    [KEY_KP8] = "8",
    [KEY_KP9] = "9",
    [KEY_SYSRQ] = " _printscreen_ ",
    [KEY_SCROLLLOCK] = " _scrolllock_ ",
    [KEY_PAUSE] = " _pause_ ",
};
